name: myusic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # For the Neumorphic UI
  flutter_neumorphic: ^3.2.0

  # Audio playback
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.9

  # Music file scanning
  on_audio_query: ^2.9.0

  # Permissions
  permission_handler: ^12.0.1

  # State management
  provider: ^6.0.5

  # UI helpers
  cached_network_image: ^3.2.3

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
